### PR TITLE
Spanish Version of why_we_collect in .config files

### PR DESCRIPTION
**Pull request by sebastiandsc**
In the join page when making the change from English to Spanish the property (key) called "why_we_collect" in the Spanish version appears as "why_we_collect_es", generating a problem because when making the dynamic change of the text of the web page does not find this key ("why_we_collect") in the JSON file when the fetch is done. Therefore, we have decided to create this property in the key "ES" in each of the JSON files of the studies.

### CODE REVIEW

**Review by shankari — CHANGES_REQUESTED** [review]
Can you please file an issue to remove the old `why_we_collect_es` key after we finish migrating the join page?

**Comment by shankari** [comment]
@dcolondavila can you please file the issue so that I can merge this?

**Comment by dcolondavila** [comment]
Will do. It will be filed at [e-mission-docs](https://github.com/e-mission/e-mission-docs).

**Comment by shankari** [comment]
@dcolondavila once it is filed, I can merge this.

**Comment by dcolondavila** [comment]
Done ✔️

**Comment by shankari** [comment]
New issue is https://github.com/e-mission/e-mission-docs/issues/844

**Comment by shankari** [comment]
Merged. Please see the additional comment in the issue.

**Pull request merged**
