### PR TITLE
Dynamic surveys

### PR DESCRIPTION
**Pull request by sebastianbarry**
Adding survey-data for each different survey into this repo (they were removed from being local to the e-mission-phone repo)

Adding surveys info into each of the study/program's config files - **These are still WIP, so let me know if you think there is a better way you believe they can be structured/missing data please!!**

### CODE REVIEW

**Comment by sebastianbarry** [comment]
@shankari and @JGreenlee Here is my first idea for how the `surveys` field will look on the deploy-config files. Let me know if this is how you'd imagined it, or if there's anything I missed or should add/change

**Comment by sebastianbarry** [comment]
I also do not know how to remove commit [7b59d0b](https://github.com/e-mission/nrel-openpath-deploy-configs/pull/7/commits/7b59d0be8c719980b77da33795e2ee4216129352), Git is giving me some issues when I try to drop it via the terminal:

image

I will pick back up on this tomorrow

**Comment by sebastianbarry** [comment]
Also, because I have changed the name of the field in the configs from `survey_paths` to `surveys`, the changes I made for the `sebastianbarry/e-mission-phone` branch `places-survey` will no longer work, this is also something I will need to revisit tomorrow to fix

**Comment by shankari** [comment]
wrt https://github.com/e-mission/nrel-openpath-deploy-configs/pull/7#issuecomment-1362216180, why do you want to remove that commit? I have had success removing the last commit in a sequence, but given that the commit history is linear, I am not sure it is easy to remove the first commit in a commit chain.

My suggestion would be to make a new branch off the current master and then cherry-pick all the commits that you want to keep. You can specify the range of cherry-picked commits, and since they are all fairly new, they should apply cleanly.

**Review by shankari — CHANGES_REQUESTED** [review]
- Why are we adding survey information to all existing configs, including production configs? The whole point of making this be configurable is that we want to have surveys in some cases and not have surveys in other cases. It seems like it would be sufficient to list the new survey fields in the dev configs for now until we get some use cases that actually need them.
- Why do we have the names "TripConfirmSurvey" and "UserProfileSurvey"? Are they linked to someplace in the code? If so, would we need to add new code every time we added a new survey type...
- Do we want to check in all the xml and xslt files into this github as well? I am not opposed to it, just wanted to make sure that we have thought through the pros/cons.

**Comment by shankari** [comment]
I know that I said that we should potentially move the `enketoSurveyConfig.json` to the dynamic config and remove it from the phone directory, but after seeing this, I think that we may want to keep the `TripConfirmSurvey` and `UserProfileSurvey` unchanged since (1) we don't need them to be dynamic just yet and (2) changing the `TripConfirmSurvey` in particular will be a problem for the UNSW group.

So for now, we should load the new trip-additions and place-additions surveys from the dynamic config and keep the `TripConfirmSurvey` and `UserProfileSurvey` from the existing `enketoSurveyConfig.json`

**Comment by sebastianbarry** [comment]
To-do:
- [ ] Move the `survey-resources` stuff from `e-mission-phone` to this `surveys` direcotry

**Comment by shankari** [comment]
I changed my mind again - if we put the new configs into the dynamic config, then UNSW will have to deal with dynamic configs anyway. So I think that we should change the `dynamic_config.js` to be able to read from local or remote dynamic configs and maybe even change the remote dynamic config location to support other apps. 

So we go back to putting everything into the dynamic config.

```
        const downloadURL = "https://raw.githubusercontent.com/e-mission/nrel-openpath-deploy-configs/main/configs/"+label+".nrel-op.json"
```

**Comment by shankari** [comment]
two options are:

```
TimeUseSurvey: {....}
place-level-additions-survey: TimeUseSurvey 
```

OR

```
place-level-additions-survey: {...}
```

**Comment by JGreenlee** [comment]
@sebastianbarry @shankari

Here's how I suggest we can go about generalizing and renaming the "time use" functionality.

`enketo-time-use-button` becomes `enketo-add-note-button`. It will take an argument 'survey'.

trip_list_item.html:
    `<enketo-add-note-button survey="trip-notes">`
place_list_item.html:
    `<enketo-add-note-button survey="place-notes">`

config structured like this
```
...
"surveys": {
    "TimeUseSurvey": {
        "formPath": ...
        ...
    }
    "place-notes": TimeUseSurvey 
    "trip-notes": TimeUseSurvey
}
...

```

In the controller, we read `$scope.survey`, find it in the config, and lookup the appropriate URL
```
const surveyKey = $scope.ui_config.surveys[$scope.survey];
if (!surveyKey) {
  console.log(`No survey found for target ${$scope.survey}. Skipping...`);
  return;
}
const survey = $scope.ui_config.surveys?.[surveyKey];

// then load by survey.formPath
```

**Comment by shankari** [comment]
@JGreenlee that sounds good in general. One final design question - where will the `ng-if` to show/hide it be?
Note that if `place-notes` is not present, for example, we do not want to display the place directive at all.
In that case, the label screen should be a list of trips.

Your original plan was to put it outside the directive (https://github.com/sebastianbarry/e-mission-phone/pull/1#discussion_r1054013451).

**Comment by JGreenlee** [comment]
@shankari 
I think either way, the config needs to be accessed in at least two places.

We have this nested structure:
> infinite_scroll_list
>>place_list_item
> > > enketo_add_note_button

The `enketo_add_note_button` needs to read dynamic config to get the appropriate formPath and labels.

And the ng-if to hide/show has to be either in `infinite_scroll_list` or `place_list_item`
Right now I'd still lean towards putting that logic in infinite_scroll_list - especially because that's where we also need to dynamically set `item-height` to get the `collection-repeat` working. (If place listitems are being shown, then the heights will be increased)

If there's a way we can avoid this boilerplate and just read the config once, that would be better - but I don't know of one

**Comment by shankari** [comment]
There *is* a global instance of `ui_config` - in `www/js/config/dynamic_config.js`
https://github.com/e-mission/e-mission-phone/blob/master_for_platform/www/js/config/dynamic_config.js#L81

The problem is that the global instance is read from the SQLite database, so it is not guaranteed to be available at the time that the directive is initialized, particularly if it is the first tab that the user interacts with. Only after the native plugins are available can the call to the database be initialized, and only after the asynchronous call to the database returns is the config available.

When I originally thought about this, I assumed that the list would listen to the config and that it would pass the survey info through to the enketo button directives through a parameter. That seems like a reasonable balance between a hard-coded config and reading the config everywhere.

aka in `infinite_scroll_list.js`
```
    $ionicPlatform.ready().then(function() {
      DynamicConfig.configChanged().then((newConfig) => {
        $scope.$apply(() => $scope.config = newConfig);
      }
   }
```

in `infinite_scroll_list.html`

```
                <infinite-scroll-trip-item trip="trip" config="config" map-limiter="mapLimiter"></infinite-scroll-trip-item>
```

**Comment by JGreenlee** [comment]
@shankari Passing it down through parameters looks like a better solution, thanks
I had been retrieving it via that promise each time, so I'll change it tomorrow

**Comment by shankari** [comment]
- Remove node_modules
- now that we don't have the `enketoSurveyConfig.json` any more, every single production deployment should have the `UserProfileSurvey`

**Comment by sebastianbarry** [comment]
This PR can be closed as I created a new PR which removes the Denver-CASR commit and is overall much cleaner and solves the problem more concisely: https://github.com/e-mission/nrel-openpath-deploy-configs/pull/8

**Pull request closed without merging**
